<?php

namespace Container7LlCP4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hz8xIV2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hz8xIV2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hz8xIV2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AuthorController::delete' => ['privates', '.service_locator.acoVuaC', 'get_ServiceLocator_AcoVuaCService', true],
            'App\\Controller\\AuthorController::edit' => ['privates', '.service_locator.acoVuaC', 'get_ServiceLocator_AcoVuaCService', true],
            'App\\Controller\\AuthorController::index' => ['privates', '.service_locator.Pe.SjzD', 'get_ServiceLocator_Pe_SjzDService', true],
            'App\\Controller\\AuthorController::new' => ['privates', '.service_locator.Pe.SjzD', 'get_ServiceLocator_Pe_SjzDService', true],
            'App\\Controller\\BooksController::delete' => ['privates', '.service_locator.52Fzhv8', 'get_ServiceLocator_52Fzhv8Service', true],
            'App\\Controller\\BooksController::edit' => ['privates', '.service_locator.52Fzhv8', 'get_ServiceLocator_52Fzhv8Service', true],
            'App\\Controller\\BooksController::index' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\BooksController::new' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\PublisherController::delete' => ['privates', '.service_locator.rT0gHHY', 'get_ServiceLocator_RT0gHHYService', true],
            'App\\Controller\\PublisherController::edit' => ['privates', '.service_locator.rT0gHHY', 'get_ServiceLocator_RT0gHHYService', true],
            'App\\Controller\\PublisherController::index' => ['privates', '.service_locator.vB4jlCr', 'get_ServiceLocator_VB4jlCrService', true],
            'App\\Controller\\PublisherController::new' => ['privates', '.service_locator.vB4jlCr', 'get_ServiceLocator_VB4jlCrService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AuthorController:delete' => ['privates', '.service_locator.acoVuaC', 'get_ServiceLocator_AcoVuaCService', true],
            'App\\Controller\\AuthorController:edit' => ['privates', '.service_locator.acoVuaC', 'get_ServiceLocator_AcoVuaCService', true],
            'App\\Controller\\AuthorController:index' => ['privates', '.service_locator.Pe.SjzD', 'get_ServiceLocator_Pe_SjzDService', true],
            'App\\Controller\\AuthorController:new' => ['privates', '.service_locator.Pe.SjzD', 'get_ServiceLocator_Pe_SjzDService', true],
            'App\\Controller\\BooksController:delete' => ['privates', '.service_locator.52Fzhv8', 'get_ServiceLocator_52Fzhv8Service', true],
            'App\\Controller\\BooksController:edit' => ['privates', '.service_locator.52Fzhv8', 'get_ServiceLocator_52Fzhv8Service', true],
            'App\\Controller\\BooksController:index' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\BooksController:new' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\PublisherController:delete' => ['privates', '.service_locator.rT0gHHY', 'get_ServiceLocator_RT0gHHYService', true],
            'App\\Controller\\PublisherController:edit' => ['privates', '.service_locator.rT0gHHY', 'get_ServiceLocator_RT0gHHYService', true],
            'App\\Controller\\PublisherController:index' => ['privates', '.service_locator.vB4jlCr', 'get_ServiceLocator_VB4jlCrService', true],
            'App\\Controller\\PublisherController:new' => ['privates', '.service_locator.vB4jlCr', 'get_ServiceLocator_VB4jlCrService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AuthorController::delete' => '?',
            'App\\Controller\\AuthorController::edit' => '?',
            'App\\Controller\\AuthorController::index' => '?',
            'App\\Controller\\AuthorController::new' => '?',
            'App\\Controller\\BooksController::delete' => '?',
            'App\\Controller\\BooksController::edit' => '?',
            'App\\Controller\\BooksController::index' => '?',
            'App\\Controller\\BooksController::new' => '?',
            'App\\Controller\\PublisherController::delete' => '?',
            'App\\Controller\\PublisherController::edit' => '?',
            'App\\Controller\\PublisherController::index' => '?',
            'App\\Controller\\PublisherController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthorController:delete' => '?',
            'App\\Controller\\AuthorController:edit' => '?',
            'App\\Controller\\AuthorController:index' => '?',
            'App\\Controller\\AuthorController:new' => '?',
            'App\\Controller\\BooksController:delete' => '?',
            'App\\Controller\\BooksController:edit' => '?',
            'App\\Controller\\BooksController:index' => '?',
            'App\\Controller\\BooksController:new' => '?',
            'App\\Controller\\PublisherController:delete' => '?',
            'App\\Controller\\PublisherController:edit' => '?',
            'App\\Controller\\PublisherController:index' => '?',
            'App\\Controller\\PublisherController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
