<?php

namespace Container7LlCP4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadAuthorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\BadAuthor' shared autowired service.
     *
     * @return \App\Command\BadAuthor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/BadAuthor.php';

        $container->privates['App\\Command\\BadAuthor'] = $instance = new \App\Command\BadAuthor(\dirname(__DIR__, 4), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\AuthorRepository'] ?? $container->load('getAuthorRepositoryService')));

        $instance->setName('app:delauthor');
        $instance->setAliases(['app:del-author']);
        $instance->setDescription('Удаление авторов без книг');

        return $instance;
    }
}
