<?php

namespace Container7LlCP4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooksControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BooksController' shared autowired service.
     *
     * @return \App\Controller\BooksController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BooksController.php';

        $container->services['App\\Controller\\BooksController'] = $instance = new \App\Controller\BooksController();

        $instance->setContainer(($container->privates['.service_locator.ghRfMDm'] ?? $container->load('get_ServiceLocator_GhRfMDmService'))->withContext('App\\Controller\\BooksController', $container));

        return $instance;
    }
}
