<?php

namespace ContainerOHtP7wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AcoVuaCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.acoVuaC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.acoVuaC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'author' => ['privates', '.errored..service_locator.acoVuaC.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.acoVuaC": it needs an instance of "App\\Entity\\Author" but this type has been excluded in "config/services.yaml".'],
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
        ], [
            'author' => 'App\\Entity\\Author',
            'authorRepository' => 'App\\Repository\\AuthorRepository',
        ]);
    }
}
