<?php

namespace ContainerOHtP7wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VB4jlCrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vB4jlCr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vB4jlCr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'publisherRepository' => ['privates', 'App\\Repository\\PublisherRepository', 'getPublisherRepositoryService', true],
        ], [
            'publisherRepository' => 'App\\Repository\\PublisherRepository',
        ]);
    }
}
