<?php

namespace ContainerOHtP7wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_52Fzhv8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.52Fzhv8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.52Fzhv8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.52Fzhv8.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.52Fzhv8": it needs an instance of "App\\Entity\\Book" but this type has been excluded in "config/services.yaml".'],
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
        ], [
            'book' => 'App\\Entity\\Book',
            'bookRepository' => 'App\\Repository\\BookRepository',
        ]);
    }
}
