<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_author' => [[], ['_controller' => 'App\\Controller\\AuthorController::index'], [], [['text', '/author/']], [], [], []],
    'app_newauthor' => [[], ['_controller' => 'App\\Controller\\AuthorController::new'], [], [['text', '/author/new']], [], [], []],
    'app_author_edit' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/author/edit']], [], [], []],
    'app_author_delete' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/author/delete']], [], [], []],
    'app_books' => [[], ['_controller' => 'App\\Controller\\BooksController::index'], [], [['text', '/books/']], [], [], []],
    'app_newbook' => [[], ['_controller' => 'App\\Controller\\BooksController::new'], [], [['text', '/books/new']], [], [], []],
    'app_book_edit' => [['id'], ['_controller' => 'App\\Controller\\BooksController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/books/edit']], [], [], []],
    'app_book_delete' => [['id'], ['_controller' => 'App\\Controller\\BooksController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/books/delete']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_publisher' => [[], ['_controller' => 'App\\Controller\\PublisherController::index'], [], [['text', '/publisher/']], [], [], []],
    'app_newpublisher' => [[], ['_controller' => 'App\\Controller\\PublisherController::new'], [], [['text', '/publisher/new']], [], [], []],
    'app_publisher_edit' => [['id'], ['_controller' => 'App\\Controller\\PublisherController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/publisher/edit']], [], [], []],
    'app_publisher_delete' => [['id'], ['_controller' => 'App\\Controller\\PublisherController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/publisher/delete']], [], [], []],
];
